name: Deploy Nestjs Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Copy project to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "."
          target: "/home/${{ secrets.EC2_USER }}/apps/api"
          rm: true
          exclude: |
            node_modules
            .git
            .github
            .env
            .env.production

      - name: Build & restart NestJS
        uses: appleboy/ssh-action@v1.0.3
        env:
          DB_URL: ${{ secrets.DB_URL }}
          PORT: ${{ secrets.PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRY: ${{ secrets.JWT_EXPIRY }}
          REFRESH_EXPIRY: ${{ secrets.REFRESH_EXPIRY }}
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            cd ~/apps/api

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

            npm install
            npm run build
            npm prune --production

            npm install -g pm2 || true

            pm2 delete api || true
            pm2 start dist/main.js \
              --name api \
              --time \
              --update-env
            pm2 save
