name: Deploy Nestjs Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js (CI only)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 3. Copy project to EC2 (keep .env.production)
      - name: Copy project to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: "."
          target: "/home/${{ secrets.EC2_USER }}/apps/api"
          rm: true
          exclude: |
            node_modules
            .git
            .github
            .env
            .env.production

      # 4. Build & restart NestJS on EC2
      - name: Build and restart Backend on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            set -e

            cd ~/apps/api

            # Load NVM
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

            node -v
            npm -v

            # Ensure PM2
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi

            # create product env
            cat > .env.production <<EOF
            NODE_ENV=production
            DB_URL=${{ secrets.DB_URL }}
            PORT=${{ secrets.PORT }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_EXPIRY=${{ secrets.JWT_EXPIRY }}
            REFRESH_EXPIRY=${{ secrets.REFRESH_EXPIRY }}
            BREVO_API_KEY=${{ secrets.BREVO_API_KEY }}
            AWS_REGION=${{ secrets.AWS_REGION }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}
            EOF
            # Install deps & build
            npm install
            npm run build

            # Prune dev deps
            npm prune --production

            # Restart API with existing env file
            pm2 delete api || true
            pm2 start dist/main.js \
              --name api \
              --env production \
              --time
            pm2 save
